[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zuvo"
version = "0.1.0"
description = "Zero-boilerplate CLI framework with i18n and compilation support"
authors = [{ name = "wipodev", email = "ajwipo@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich==15.0.0",
    "babel==2.18.0",
    "tomlkit==0.15.1",
]

[project.optional-dependencies]
pypi = ["build==1.5.0", "hatchling==1.31.0"]
pyinstaller = ["pyinstaller==6.21.0"]
nuitka = ["nuitka>=4.1.3"]
build-tools = [
    "zuvo[pypi]",
    "zuvo[pyinstaller]",
    "zuvo[nuitka]",
]
test = [
    "pytest==9.1.1",
]
dev = [
    "zuvo[pypi]",
    "zuvo[test]",
]
all = [
    "zuvo[build-tools]",
    "zuvo[test]",
]

[project.scripts]
zuvo = "zuvo.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/zuvo"]

[tool.hatch.build.targets.wheel.force-include]
"src/zuvo/template" = "zuvo/template"
"src/zuvo/locales" = "zuvo/locales"

[tool.zuvo]
title = "Zuvo Framework"
copyright = "© 2026 WipoDev. All Rights Reserved."
commands_pkg = "zuvo.commands"

[tool.zuvo.commands]
zuvo = ["init", "create", "install", "run", "build", "package"]

[tool.zuvo.build]
cli_name = "zuvo"
entry_point = "src/zuvo/cli.py"
compiler = "pypi"