[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zuvo"
version = "0.0.1.dev1"
description = "Zero-boilerplate CLI framework with i18n and compilation support"
authors = [{ name = "wipodev", email = "ajwipo@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich==15.0.0",
    "babel==2.18.0",
]

[project.optional-dependencies]
dev = [
    "pytest==9.1.1",
]

[project.scripts]
zuvo = "zuvo.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/zuvo"]

[tool.hatch.build.targets.wheel.force-include]
"src/zuvo/template" = "zuvo/template"

[tool.zuvo]
title = "Zuvo Framework"
copyright = "© 2026 WipoDev. All Rights Reserved."
commands_pkg = "zuvo.commands"

[tool.zuvo.commands]
zuvo = ["init", "run", "build", "package"]