[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cli_test"
version = "0.1.0"
description = "test project"
authors = [
    { name = "WipoDev" }
]

[project.scripts]
cli_test = "app.main:main"

[tool.zuvo]
title = "Python CLI Test"
copyright = "© 2026 WipoDev. All Rights Reserved."
commands_pkg = "app.commands"

[tool.zuvo.commands]
cli_test = ["install", "create"]

[tool.zuvo.build]
cli_name = "cli_test"
entry_point = "src/app/main.py"